import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav className="bg-gray-800 text-white p-4">
          <div className="container mx-auto flex space-x-4">
            <a href="/" className="hover:underline">
              Oversigt
            </a>
            <a href="/tiers" className="hover:underline">
              Trin
            </a>
            <a href="/savings" className="hover:underline">
              Opsparing
            </a>
            <a href="/investments" className="hover:underline">
              Investering
            </a>
          </div>
        </nav>    
        {children}
      </body>
    </html>
  );
}
